spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/guli
  application:
    name: service-cms
  profiles:
    active: dev
  jackson:    #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.110.151
    port: 6379
    database: 0
    timeout: 1800000ms

#  cloud:               #//nacos注册地址
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8004
#过滤target打包没有mapper
mybatis-plus:
  mapper-locations: classpath:com/kun/eduservice/mapper/xml/*xml
#logging:
#  level:
#   root: WARN

#开启nacos熔断
#feign:
#  circuitbreaker:
#    enabled: true
#设置熔断最长时间
#redis设置
