server:
  port: 8005
spring:
  application:
    name: service-msm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: 192.168.110.151
    port: 6379
    database: 0
    timeout: 1800000ms
  profiles:
    active: dev
  jackson:    #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
tengxun:
  sms:
    secretId: KID4ycz5wXrte8LHwLSIr9AuMXS6UaQzHI2
    secretKey: UhdHgofEWXHmCLDn6B0Yprc7LJ0QZR3N
    #短信应用 ID
    appid: 1400568206
    #短信签名内容
    sign: 402640
    #短信模板ID
    templateID: 1108266
#AKID4ycz5wXrte8LHwLSIr9AuMXS6UaQzHI2
#UhdHgofEWXHmCLDn6B0Yprc7LJ0QZR3N